name: routing
channels:
- conda-forge
dependencies:
- python=3.10
- bokeh
- cartopy
- geopy
- geoviews-core
- holoviews
- hvplot
- intake
- intake-xarray
- netcdf4
- notebook
- numpy
- pandas
- gcsfs
- xarray
- zarr
- zstandard
- jupyter_bokeh
- pykdtree
- numba>=0.59
